markdown: rdiscount
permalink: /:title/
url: http://jeffreyWang.com
name: JeffreyWang
author: JeffreyWang
email: w.zhengjie10@gmail.com
duoshuo: stackvoid
cnzz: 1000413857
weibo: 208121119
github: JefferyWong
pygments: true
safe: true
paginate: 20
about: "Jeffrey's Life."
