markdown: rdiscount
permalink: /:title/
url: http://stackvoid.com
name: StackVoid
author: stackvoid
email: pfming1989@gmail.com
duoshuo: stackvoid
cnzz: 1000413857
weibo: 539110127
github: stackvoid
pygments: true
safe: true
paginate: 20
about: "Stackvoid's Attitude."
qq: 578590963
